apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-xfek
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-wkmf-tenant/rhtap-demo-app/hacbs-test-project-xfek@sha256:2560ecaef366b3645cbb48c1c69346cf6e7e8cb8d7123fa5cce02a0f58a3d6e8
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
