apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-xfek
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-xfek
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-xfek
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-xfek
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-xfek
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-wkmf-tenant/rhtap-demo-app/hacbs-test-project-xfek@sha256:2560ecaef366b3645cbb48c1c69346cf6e7e8cb8d7123fa5cce02a0f58a3d6e8
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
